packages:
  - "apps/*"
  - "libs/*"
  - "../extends-zustand"
  - "../extends-antd"
  - "../extends-ssh"
  - "../remote-runtimeobj/webrtcsignaling"
  - "../create-todo-cli/mcpCreate"
  - "../create-todo-cli/src"
