packages:
  - "apps/*"
  - "libs/*"
  - "../extends-zustand"
  - "../extends-antd"
  - "../extends-ssh/ubuntu-lib"
  - "../remote-runtimeobj/webrtcsignaling"
  - "../create-todo-cli/create-todo-mcp"
  - "../create-todo-cli/create-todo-src"
